GradientBoostingRegressor:
  random_search:    
    n_estimators: [50, 100, 200]
    learning_rate: [0.01, 0.1, 0.2]
    max_depth: [3, 4, 5]
    min_samples_split: [2, 5, 10]
    min_samples_leaf: [1,2,3,4]
    subsample: [0.6, 0.8, 1.0]



  cross_validation:  
    cv_folds: 5
    scoring: "r2"
    n_jobs: -1
    n_iter: 1

train_test_split:
 test_size: 0.2
 random_state: 42

